### ISSUE TITLE
Was sind die CPU- und RAM-Anforderungen von Simi

### ISSUE THREAD

**Issue by schmandr** [sogis/simi#18]
Jetzt machen wir mal die Probe aufs Exempel:

In https://github.com/simi-so/simi/blob/7b62ee9635c76ff23a7552cb9b39a00521690a84/openshift/simi-integration.env#L7-L10 müsste ich noch CPU- und RAM-Anforderungen eintragen. Kann der Entwickler der Software sagen, was die so etwa sind?

Aus dem Betrieb sehe ich heraus: Während dem Start ewtas über 0.75 Cores, danach unter 0.1 Cores. RAM im Moment 860 MB.(Wobei diese Werte häufig mit Vorsicht zu geniessen sind.)

**Comment by edigonzales** [comment]
Es ist eine Spring Boot Anwendung. Ich glaube immer noch, dass man für diese Dinger einen Request (mind. 0.5) setzt aber kein Limit. Aber Oliver soll entscheiden.
